spring:
  datasource:
    url: jdbc:mysql://192.168.2.128:3306/pizza
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.ddos.pizza.mapper
  mapperLocations: classpath:com.ddos.pizza.mapper/*.xml