spring:
  datasource:
    url: jdbc:mysql://192.168.2.132:3306/pizza
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
mybatis:
  typeAliasesPackage: com.ddos.pizza.mapper
  mapperLocations: classpath:com.ddos.pizza.mapper/*.xml